#!/bin/bash
#
# Host-side bring-up for the Voltempo SIL stack. Run this from your own shell, not inside the
# container: ./.devcontainer/sil-up.sh
#
# It exists because `docker compose up` on its own does not work here, for three reasons that each
# fail in a different and unhelpful way:
#
#   1. The everest-build volume is declared `external: true`, so compose will not create it. On a
#      machine that has never built EVerest, `up` aborts with
#      `external volume "everest-build" not found` before anything starts. It is external on purpose:
#      it holds an ~11 GB build, and `docker compose down -v` must not be able to delete it.
#   2. Three compose files have to be passed, in order. Miss docker-compose.buildvol.yml and the
#      container comes up with no /build mount and no autostart - a shell with no EVerest in it.
#   3. .env carries this machine's UID, GID and absolute workspace path, so it is gitignored and has
#      to be generated locally.
#
# Everything here is idempotent - run it as often as you like.
#
# Arguments are passed through to `docker compose up`, so:
#     ./.devcontainer/sil-up.sh --force-recreate     after changing command: or an EVEREST_* value
#
# Environment:
#     COMPOSE_PROJECT_NAME   compose project (default devcontainer, which names containers
#                            devcontainer-devcontainer-1 and so on)

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${HERE}/.." && pwd)"
PROJECT="${COMPOSE_PROJECT_NAME:-devcontainer}"
BUILD_VOLUME=everest-build

say() { echo "[sil-up] $*"; }
die() { echo "[sil-up] $*" >&2; exit 1; }

command -v docker > /dev/null || die "docker is not on PATH"

# 1. The build volume. Created empty if absent; step 4 of .devcontainer/README.md fills it.
if docker volume inspect "${BUILD_VOLUME}" > /dev/null 2>&1; then
    say "volume ${BUILD_VOLUME} present"
else
    say "creating volume ${BUILD_VOLUME} - it is empty, so EVerest still needs building (see README)"
    docker volume create "${BUILD_VOLUME}" > /dev/null
fi

# 2. .env. Generated rather than copied from .env.example, because every value that differs between
#    machines is one this shell can answer for itself.
if [[ -f "${HERE}/.env" ]]; then
    say ".env present"
else
    say "generating .env for this machine"

    # Matches what applications/devrd/devrd resolves. Non-fatal: the build arg has a default, and a
    # developer with no network should still get a usable .env.
    commit_hash="$(git ls-remote https://github.com/EVerest/everest-dev-environment.git main 2>/dev/null | cut -f1 || true)"
    [[ -n "${commit_hash}" ]] || say "warning: could not resolve everest-dev-environment main - leaving COMMIT_HASH blank"

    cat > "${HERE}/.env" <<EOF
# Generated by .devcontainer/sil-up.sh - machine-specific, gitignored.
# See .env.example for what each value means.
ORGANIZATION_ARG=EVerest
REPOSITORY_HOST=github.com
REPOSITORY_USER=git
COMMIT_HASH=${commit_hash}
EVEREST_TOOL_BRANCH=main
UID=$(id -u)
GID=$(id -g)
HOST_WORKSPACE_FOLDER=${REPO}
EOF
fi

# 3. Compose. The file order is load-bearing: buildvol.yml is last so its command: and /build mount
#    win over the stock devcontainer definition.
say "starting the sil profile as project '${PROJECT}'"

docker compose \
    --project-directory "${HERE}" \
    -p "${PROJECT}" \
    -f "${HERE}/docker-compose.yml" \
    -f "${HERE}/general-devcontainer/docker-compose.devcontainer.yml" \
    -f "${HERE}/docker-compose.buildvol.yml" \
    --profile sil \
    up -d "$@"

say "done - follow EVerest with: docker logs -f ${PROJECT}-devcontainer-1"
